### ISSUE TITLE
Create Task Object and Services

### ISSUE THREAD

**Issue by emmalynfoster** [emmalynfoster/task-manager#2]
This feature will act as the table for `Task` for storing tasks a user makes in our database and include services for interacting with the database. 

## Why? 
This will allow us to store the users tasks in order to keep track of their completion and interact with them from the frontend. 

## Acceptance Criteria 
 - [x] Task Entity object with fields id as primary key, title, description, due date, complete (boolean), and category
 - [x] Category must be populated with enums for designated task categories 
 
Services: 
 - [x] Create task
 - [x] Get all tasks
 - [x] Get task by id
 - [x] Update task
 - [x] Delete task

**Comment by ojhern24** [comment]
All criteria here is completed.
