### ISSUE TITLE
Create APIs for Services

### ISSUE THREAD

**Issue by emmalynfoster** [emmalynfoster/task-manager#4]
This feature will create APIs that connect backend and frontend service layers for both Task and To-do. It should generally be in one API file. 

## Why? 
This will allow the transfer of data through HTTP requests for user interaction through backend and frontend services. 

## Acceptance Criteria 
- [x] APIs should generally match the backend services for Task and To-do objects, as they are going to call them
- [x] We must include 1 3rd party API
- [x] Get all tasks
- [x] Get one task by id
- [x] Create (post) a task
- [x] Update (put) a task 
- [x] Delete a task
- [x] Create a to-do item 
- [x] Delete a to-do item
- [x] Get a to-do item

**Comment by Zehraacu** [comment]
> This feature will create APIs that connect backend and frontend service layers for both Task and To-do. It should generally be in one API file. 
> 
> ## Why? 
> This will allow the transfer of data through HTTP requests for user interaction through backend and frontend services. 
> 
> ## Acceptance Criteria 
> - [ ] APIs should generally match the backend services for Task and To-do objects, as they are going to call them
> - [ ] We must include 1 3rd party API
> - [ ] Get all tasks
> - [ ] Get one task by id
> - [ ] Create (post) a task
> - [ ] Update (put) a task 
> - [ ] Delete a task
> - [ ] Create a to-do item 
> - [ ] Delete a to-do item
> - [ ] Get a to-do item

- >

**Comment by ojhern24** [comment]
Everything here should be complete as long as https://github.com/emmalynfoster/task-manager/pull/28 is sufficient to be considered as third party API inclusion.
